### ISSUE TITLE
Issue with flake.nix not finding input for 'beautysh/flak-utils'

### ISSUE THREAD

**Issue by sweenu** [lovesegfault/beautysh#148]
I have the following error when doing `nix flake update`:
```
error: input 'bud/beautysh/poetry2nix/flake-utils' follows a non-existent input 'beautysh/flake-utils'
```

I'm guessing this is related to the 10-day-old commits refactoring the flake.nix.

**Comment by lovesegfault** [comment]
The input is called `utils` now, so you need to do `beautysh.inputs.utils.follows = "flake-utils"`. Sorry for the churn!
