### ISSUE TITLE
Unexpected indent after empty line

### ISSUE THREAD

**Issue by mdeweerd** [lovesegfault/beautysh#207]
`beautysh` 6.2.1 formats the following script

```shell
#!/bin/bash

# List of options to optionnaly add to pandoc
# -V title="${INFILE}" \
# -V geometry:"top=2cm, bottom=1.5cm, left=2cm, right=1cm" \
# --variable fontsize=24pt \
# -V lang=fr \

pandoc \
    --variable fontsize=24pt \
    some other option
```

like this:

```shell
#!/bin/bash

# List of options to optionnaly add to pandoc
# -V title="${INFILE}" \
  # -V geometry:"top=2cm, bottom=1.5cm, left=2cm, right=1cm" \
  # --variable fontsize=24pt \
  # -V lang=fr \

  pandoc \
  --variable fontsize=24pt \
  some other option
```

I do not expect "pandoc \" to be indented with regards to the comments preceding it.

I would also argue that comments at the start of a line (or preceded with spaces) ending in a line continuation should not be indented.

**Comment by devenes** [comment]
Hi @mdeweerd,

> I do not expect "pandoc " to be indented with regards to the comments preceding it.

You can follow this pattern: 

```bash
#!/bin/bash

# List of options to optionnaly add to pandoc
# -V title="${INFILE}" \
    # -V geometry:"top=2cm, bottom=1.5cm, left=2cm, right=1cm" \
    # --variable fontsize=24pt \
    # -V lang=fr

pandoc \
    --variable fontsize=24pt \
    some other option
```

If you want to use a new block of code you can remove the `\` at the end of the line, `-V lang=fr`.

**Comment by mdeweerd** [comment]
Well, the idea is to be able to cut/paste the line as an option again and just remove the "#".

I take it that we have different views on how this should work.
