### ISSUE TITLE
Sublime Text plugin

### ISSUE THREAD

**Issue by harshit22394** [lovesegfault/beautysh#21]
Hi @bemeurer Can you create a sublime text plugin for this. It would be really helpful for a lot of sublime text users like me.

**Comment by jwhonce** [comment]
I don't use Sublime nor speak for @bemeurer but https://github.com/joysboy/SublimeBashTidy may fill your needs.

**Comment by bemeurer** [comment]
Sorry for the delay, I've been traveling too much. I'd be interested in making a Sublime plugin for beautysh (even though it was created solely because Atom's atom-beautify needed a Bash solution, hehe). I'll look into it.

**Comment by lovesegfault** [comment]
Fixed on #54.
