### ISSUE TITLE
Feature request: Convert test ([) to new form ([[)

### ISSUE THREAD

**Issue by donovan** [lovesegfault/beautysh#46]
It would be nice if beautysh had an option to replace old test format with new eg:

    if [ "$foo" == "$bar" ]; then

becomes

    if [[ "$foo" == "$bar" ]]; then

Personally I would prefer the variables to remain quoted in this case even thought it is optional with the `[[` form.

Examples:

    find . -name '*.sh' -exec grep -H 'if \[ ' {} \;

The reverse would also be good for people who want to write portable code. Could be implemented in a similar way to `--force-function-style` ie:

    --force-test-style bash|compatible

    Shell test styles that can be specified via --force-test-style are:
    compatible: single bracket test compatible with sh, e.g.     if [ "$foo"
    bash: double bracket test used by bash and zsh, e.g.   if [[ "$foo"

**Comment by RubenKelevra** [comment]
I doubt that's a good idea. The behavior of single vs double brackets has many edge cases that need to be dealt with, to do 1:1 translations.

See here for some examples:
https://stackoverflow.com/a/47576482

**Comment by lovesegfault** [comment]
I'll second @RubenKelevra; I find this to be more of an anti-feature since it replaces things which are not semantically equivalent.
