### ISSUE TITLE
missing dependency: ImportError: No module named 'setuptools'

### ISSUE THREAD

**Issue by alexandrufulop** [lovesegfault/beautysh#47]
The following:
```$python setup.py```

throughs this error:

Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from setuptools import setup
ImportError: No module named setuptools

Please add to docs the dependency for: 

[SOLUTION]

To install setuptools on Debian, Ubuntu or Mint:
$ ```sudo apt-get install python-setuptools```

For Python 3.X applications, install python3-setuptools instead.
$ ```sudo apt-get install python3-setuptools```

On Red Hat based systems, setuptools comes pre-installed. For whatever reason if you want to install it, use the yum command.
$ ```sudo yum python-setuptools```

Thanks!

**Comment by lovesegfault** [comment]
Hi @alexandrufulop thanks for the report!

Beautysh itself has no dependencies, setuptools is a dependency to _any_ Python setup script, thus the issue you faced. In other words, setuptools is not required to use beautysh, only to deal with the Python installer, which is optional.
