### ISSUE TITLE
Intent to package: Snaps are universal Linux packages

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [lovesegfault/beautysh#52]
Dear maintainer(s), 

[Snaps are universal Linux packages](https://snapcraft.io) that can be installed and run on many GNU+Linux distributions with ease.  I've been following the [Snapcrafters](https://forum.snapcraft.io/t/join-snapcrafters/1325) instructions and [have built a working snap on the Snap Store](https://snapcraft.io/beautysh), you may try it by running the following commands after [installing snapd](https://docs.snapcraft.io/installing-snapd/6735):
 
    sudo snap install beautysh

I'm also looking forward to working with you to make the packaging work upstream (if you're interested).  You may want to check out the current [packaging recipe](https://github.com/snap-dump/beautysh-snap), the [documentation](https://docs.snapcraft.io), registering a developer account on the [Snap Store](https://snapcraft.io/store), and [get in touch with us](https://forum.snapcraft.io) to transfer the work under your control.

Thanks for your time and attention.

**Comment by lovesegfault** [comment]
Hi @Lin-Buo-Ren !

I really appreciate you taking the time to package Beautysh for Snap, thank you!

As a Gentoo user, I cannot locally test Snap packages, but nonetheless I'd be happy to maintain the Snap formula and use an Arch container to do the testing. Let me know how to proceed in taking ownership of it.
