### ISSUE TITLE
Removed -f flag broke atom-beautify integration

### ISSUE THREAD

**Issue by fleXible** [lovesegfault/beautysh#59]
Hello,
your PR #49 unnecessarily broke the integration with [atom-beautify](https://atom.io/packages/atom-beautify) which is rather sad. After reading the comments I am sad about this little respect to other peoples work and time.

In the end, "bumping the major version" as you described, didn't really help me much in getting my scripts nicer!

<img width="463" alt="beautysh error in atom-beautify " src="https://user-images.githubusercontent.com/2601493/65376218-bcfa3080-dc9d-11e9-8642-b69459849e5e.png">

Please either put the parameter back in, at least for a while, or inform the maintainers of [atom-beautify](https://atom.io/packages/atom-beautify) about this change.

**Comment by lovesegfault** [comment]
> your PR #49 unnecessarily broke the integration with atom-beautify which is rather sad.

Unnecessarily is for me, the person putting in the work to keep this thing running, to judge; not you.

>  I am sad about this little respect to other peoples work and time.

Have respect for _my_ work and time and fix this downstream yourself.

> Please either put the parameter back in

No.

> inform the maintainers of atom-beautify about this change.

https://github.com/Glavin001/atom-beautify/pull/2385

Next time you want someone to help you, @fleXible, be less edgy and more nice.

**Comment by fleXible** [comment]
I helped myself just by installing the older version.

> Whether or not it was necessary is for me, the person putting in the work to keep this thing running, to judge; not you.
Actually no. Usually it starts with an Issue describing and discussing the necessity of a change before implementing it. So that other people are involved in the decision making process and others later to follow the reasoning.

> Next time you want someone to help you, @fleXible, be less edgy and more nice.
And yes, I am a bit edgy, because of the above. Sorry for that.
