### ISSUE TITLE
Beautified BASH scripts are defunct.

### ISSUE THREAD

**Issue by mrphax0r** [lovesegfault/beautysh#61]
Beautysh is currently not usable for BASH scripts.
List of modifications that change the meaning of statements:
``
- [[ ... ]] statements are changed into [[...]] , which breaks conditionals.
- $() is changed into $ () , which breaks command substitution
- VARIABLE=VALUE statements get changed into VARIABLE = VALUE , which breaks variable assignments.
- Spaces are added to file paths, e.g. /path/file changes into /path / file ,which breaks file paths
- "[]" statements, which shouldn't even be interpreted because they're encased in double quotes get linebroken.
``

**Comment by lovesegfault** [comment]
Can you give me a source sample where these defects happen?

**Comment by lovesegfault** [comment]
Closing due to lack of data
