### ISSUE TITLE
beautysh change line endings character during formatting

### ISSUE THREAD

**Issue by karstenrenhak** [lovesegfault/beautysh#62]
Hi,

I'd like to run beautysh in a Windows 10 (Python 3.8) environment to format a bunch of shell scripts.
These scripts all have a new line character `\n` but after the beautysh run the new line character was changed to `\r\n`.

Now the scripts couldn't execute on a Linux or Unix system and they are useless.

Is there a way to preserve the original line separator character?
By the the way, using beautysh in Linux/Unix environment is not an option at the moment.

**Comment by lovesegfault** [comment]
@karstenrenhak thanks for the bug report!

Could you test the latest master to see whether 70ebbf5 fixed it? I don't have a Windows machine to test on.

**Comment by karstenrenhak** [comment]
Hi @lovesegfault, thanks for the prompt response.
Your fix solved this problem.
Thanks a lot.
