### ISSUE TITLE
Instalation error via git

### ISSUE THREAD

**Issue by TheRussianHetzer** [lovesegfault/beautysh#71]
I'm trying to install beautysh via git. I used those commands:
```
git clone https://github.com/lovesegfault/beautysh
cd beautysh
python setup.py install
```
I get this error code:
```
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from setuptools import setup
ImportError: No module named setuptools
```

**Comment by lovesegfault** [comment]
You must install setuptools for your system.

**Comment by TheRussianHetzer** [comment]
Could it be added that this package should be installed in the README file?
```sudo apt-get install -y python-setuptools``` for Debian distributions and ```sudo pacman -Sy python-setuptools``` for Arch distributions.

**Comment by lovesegfault** [comment]
I think that's out of scope for our docs, since _any_ python package will require `setuptools`. 

The next user who hits this will, hopefully, find this issue and the solution :)
