### ISSUE TITLE
Feature request: Support indentation with tabs

### ISSUE THREAD

**Issue by abrahammurciano** [lovesegfault/beautysh#73]
It would be great if i had an option to use tabs instead of spaces, or if the formatter would respect the setting that my file is set to rather than replace all my tabs with spaces every time I format it.

**Comment by lovesegfault** [comment]
You can use `--tab` to enforce indenting with tabs instead of spaces.

**Comment by abrahammurciano** [comment]
> You can use `--tab` to enforce indenting with tabs instead of spaces.

And where, pray tell, would I put said `--tabs`?

**Comment by lovesegfault** [comment]
I'm not sure, you want to bring that up to whoever maintains the VSCode extension (it's not me).
